package main

import (
	"go/ast"
	"strings"
)

// IsGeneratedFile checks whether the given AST file is a generated file
// by inspecting the first comment group for the "Code generated" substring.
// This follows the Go convention where generated files start with a comment like:
//
//	// Code generated by <tool>. DO NOT EDIT.
func IsGeneratedFile(file *ast.File) bool {
	if file == nil {
		return false
	}
	if len(file.Comments) == 0 {
		return false
	}

	firstGroup := file.Comments[0]
	return strings.Contains(firstGroup.Text(), "Code generated")
}
