package main

import (
	"fmt"
	"go/parser"
	"go/token"
	"testing"

	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
)

func TestProperty_GeneratedFileExclusion(t *testing.T) {
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 100
	properties := gopter.NewProperties(parameters)

	// Various generated file headers that should all be detected
	headers := []string{
		"// Code generated by protoc-gen-go. DO NOT EDIT.",
		"// Code generated by stringer -type=Pill. DO NOT EDIT.",
		"// Code generated by cmd/cgo. DO NOT EDIT.",
		"// Code generated by go generate; DO NOT EDIT.",
		"// Code generated by mockgen. DO NOT EDIT.",
	}

	properties.Property("any file with Code generated header is detected as generated", prop.ForAll(
		func(headerIdx int) bool {
			header := headers[headerIdx%len(headers)]
			src := fmt.Sprintf("%s\npackage main\n\nfunc main() {\n\tvar s []int\n\tfor i := 0; i < 10; i++ {\n\t\ts = append(s, i)\n\t}\n\t_ = s\n}\n", header)

			fset := token.NewFileSet()
			file, err := parser.ParseFile(fset, "generated.go", src, parser.ParseComments)
			if err != nil {
				return true // skip if can't parse
			}

			return IsGeneratedFile(file)
		},
		gen.IntRange(0, 499),
	))

	properties.TestingRun(t)
}
